/**
 * Registers the local HTTP Android bridge provider with `ctx.mobile`.
 * @module @deepseek-ai/dsh-mobile-bridge-http
 */

import type { Context } from '@deepseek-ai/cordis'
import z from '@deepseek-ai/schemastery'
import type {} from '@deepseek-ai/dsh-mobile'
import {
  AndroidHttpBridgeProvider,
  DEFAULT_ANDROID_BRIDGE_URL,
} from './provider.ts'

export {
  ANDROID_HTTP_PROVIDER_ID,
  AndroidHttpBridgeProvider,
  DEFAULT_ANDROID_BRIDGE_URL,
} from './provider.ts'
export type { AndroidHttpBridgeOptions } from './provider.ts'

/** Cordis plugin name used by loader diagnostics. */
export const name = 'mobile-bridge-http'

/** The mobile seam this provider registers into. */
export const inject = ['mobile']

/** HTTP bridge provider config. */
export interface Config {
  /** Local Android bridge base URL. */
  readonly baseUrl?: string
  /** Bearer token generated by the Android app. Defaults to `DSH_ANDROID_BRIDGE_TOKEN`. */
  readonly token?: string
  /** Request timeout in milliseconds. */
  readonly timeoutMs?: number
}

export const Config: z<Config> = z.object({
  baseUrl: z.string().default(DEFAULT_ANDROID_BRIDGE_URL),
  token: z.string(),
  timeoutMs: z.number().default(30_000),
})

/** Register the Android localhost HTTP provider. */
export function apply(ctx: Context, config: Config): void {
  const baseUrl = config.baseUrl ?? DEFAULT_ANDROID_BRIDGE_URL
  const timeoutMs = config.timeoutMs ?? 30_000
  if (!Number.isInteger(timeoutMs) || timeoutMs < 1) {
    throw new Error('mobile-bridge-http: timeoutMs must be a positive integer')
  }
  const token = config.token ?? process.env.DSH_ANDROID_BRIDGE_TOKEN
  if (token === undefined || token.length === 0) {
    throw new Error('mobile-bridge-http: token is required through config or DSH_ANDROID_BRIDGE_TOKEN')
  }
  ctx.mobile.registerProvider(new AndroidHttpBridgeProvider({
    baseUrl,
    token,
    timeoutMs,
  }))
}
