/**
 * HTTP transport provider for the Android Tool Bridge.
 * @module @deepseek-ai/dsh-mobile-bridge-http/provider
 */

import type {
  AndroidBridgeHealth,
  AndroidBridgeProvider,
  AndroidToolDefinition,
  AndroidToolError,
  AndroidToolRequest,
  AndroidToolResponse,
} from '@deepseek-ai/dsh-mobile'
import { MobileError } from '@deepseek-ai/dsh-mobile'

/** Default Android bridge URL exposed by Banyan. */
export const DEFAULT_ANDROID_BRIDGE_URL = 'http://127.0.0.1:8765'

/** Stable provider id for the local Android bridge HTTP transport. */
export const ANDROID_HTTP_PROVIDER_ID = 'android-http'

/** HTTP provider runtime options. */
export interface AndroidHttpBridgeOptions {
  /** Local Android bridge base URL. */
  readonly baseUrl: string
  /** Bearer token generated by the Android bridge service. */
  readonly token: string
  /** Request timeout in milliseconds. */
  readonly timeoutMs: number
}

/** Android bridge provider backed by `fetch` over localhost HTTP. */
export class AndroidHttpBridgeProvider implements AndroidBridgeProvider {
  readonly id = ANDROID_HTTP_PROVIDER_ID

  constructor(private readonly options: AndroidHttpBridgeOptions) {}

  available(): boolean {
    return this.options.token.length > 0
  }

  health(signal?: AbortSignal): Promise<AndroidBridgeHealth> {
    return this.fetchJson('/health', {
      method: 'GET',
      ...signal !== undefined ? { signal } : {},
    }).then(parseBridgeHealth)
  }

  execute(request: AndroidToolRequest, signal?: AbortSignal): Promise<AndroidToolResponse> {
    return this.fetchJson('/execute', {
      method: 'POST',
      body: JSON.stringify(request),
      acceptBridgeErrorResponse: true,
      ...signal !== undefined ? { signal } : {},
    }).then(parseToolResponse)
  }

  private async fetchJson(path: string, request: BridgeFetchRequest): Promise<unknown> {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(new Error('Android bridge request timed out')), this.options.timeoutMs)
    const abortFromCaller = (): void => controller.abort(request.signal?.reason)
    if (request.signal !== undefined) {
      if (request.signal.aborted) controller.abort(request.signal.reason)
      else request.signal.addEventListener('abort', abortFromCaller, { once: true })
    }
    try {
      const init: RequestInit = {
        method: request.method,
        headers: {
          authorization: `Bearer ${this.options.token}`,
          ...request.body !== undefined ? { 'content-type': 'application/json' } : {},
        },
        signal: controller.signal,
        ...request.body !== undefined ? { body: request.body } : {},
      }
      const response = await fetch(new URL(path, this.options.baseUrl), init)
      const value: unknown = await response.json()
      if (!response.ok) {
        if (request.acceptBridgeErrorResponse === true && isBridgeExecutionResponse(value)) {
          return value
        }
        throw new MobileError(`Android bridge HTTP ${response.status}: ${errorMessageFromResponse(value)}`, 'MOBILE_BRIDGE_HTTP_ERROR')
      }
      return value
    } catch (error: unknown) {
      if (error instanceof MobileError) throw error
      throw new MobileError(`Android bridge request failed: ${errorMessage(error)}`, 'MOBILE_BRIDGE_REQUEST_FAILED', { cause: error })
    } finally {
      clearTimeout(timeout)
      if (request.signal !== undefined) request.signal.removeEventListener('abort', abortFromCaller)
    }
  }
}

interface BridgeFetchRequest {
  readonly method: 'GET' | 'POST'
  readonly signal?: AbortSignal
  readonly body?: string
  readonly acceptBridgeErrorResponse?: boolean
}

/** Extract an error message from an Android bridge error response. */
function errorMessageFromResponse(value: unknown): string {
  if (typeof value === 'object' && value !== null) {
    const error = (value as { readonly error?: unknown }).error
    if (typeof error === 'object' && error !== null) {
      const message = (error as { readonly message?: unknown }).message
      if (typeof message === 'string') return message
    }
  }
  return 'request rejected'
}

/** Render an unknown thrown value for diagnostics. */
function errorMessage(value: unknown): string {
  return value instanceof Error ? value.message : String(value)
}

/** Parse `/health`, rejecting malformed Android bridge JSON at the provider boundary. */
function parseBridgeHealth(value: unknown): AndroidBridgeHealth {
  const record = objectRecord(value, 'health response')
  const status = enumString(record.status, ['stopped', 'listening', 'connected', 'error'], 'health.status')
  const version = stringField(record.version, 'health.version')
  const tools = arrayField(record.tools, 'health.tools').map((tool, index) => parseToolDefinition(tool, `health.tools[${index}]`))
  return { status, version, tools }
}

/** Parse `/execute`, rejecting malformed Android bridge JSON at the provider boundary. */
function parseToolResponse(value: unknown): AndroidToolResponse {
  const record = objectRecord(value, 'execute response')
  const error = record.error === null ? null : parseToolError(record.error, 'execute.error')
  return {
    id: stringField(record.id, 'execute.id'),
    ok: booleanField(record.ok, 'execute.ok'),
    result: objectRecord(record.result, 'execute.result'),
    error,
    durationMs: finiteNumberField(record.durationMs, 'execute.durationMs'),
  }
}

function isBridgeExecutionResponse(value: unknown): boolean {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false
  const record = value as Record<string, unknown>
  return typeof record.id === 'string' &&
    typeof record.ok === 'boolean' &&
    typeof record.result === 'object' &&
    record.result !== null &&
    !Array.isArray(record.result) &&
    typeof record.durationMs === 'number'
}

function parseToolDefinition(value: unknown, path: string): AndroidToolDefinition {
  const record = objectRecord(value, path)
  return {
    name: stringField(record.name, `${path}.name`),
    risk: enumString(record.risk, ['read_only', 'reversible', 'external_side_effect', 'sensitive'], `${path}.risk`),
    description: stringField(record.description, `${path}.description`),
  }
}

function parseToolError(value: unknown, path: string): AndroidToolError {
  const record = objectRecord(value, path)
  const recoveryHint = record.recoveryHint === undefined
    ? undefined
    : stringField(record.recoveryHint, `${path}.recoveryHint`)
  return {
    code: stringField(record.code, `${path}.code`),
    message: stringField(record.message, `${path}.message`),
    ...recoveryHint !== undefined ? { recoveryHint } : {},
  }
}

function objectRecord(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new MobileError(`Android bridge ${path} must be an object`, 'MOBILE_BRIDGE_INVALID_RESPONSE')
  }
  return value as Record<string, unknown>
}

function arrayField(value: unknown, path: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new MobileError(`Android bridge ${path} must be an array`, 'MOBILE_BRIDGE_INVALID_RESPONSE')
  }
  return value
}

function stringField(value: unknown, path: string): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new MobileError(`Android bridge ${path} must be a non-empty string`, 'MOBILE_BRIDGE_INVALID_RESPONSE')
  }
  return value
}

function booleanField(value: unknown, path: string): boolean {
  if (typeof value !== 'boolean') {
    throw new MobileError(`Android bridge ${path} must be a boolean`, 'MOBILE_BRIDGE_INVALID_RESPONSE')
  }
  return value
}

function finiteNumberField(value: unknown, path: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new MobileError(`Android bridge ${path} must be a finite number`, 'MOBILE_BRIDGE_INVALID_RESPONSE')
  }
  return value
}

function enumString<const Values extends readonly string[]>(value: unknown, values: Values, path: string): Values[number] {
  if (typeof value === 'string' && values.includes(value)) return value
  throw new MobileError(`Android bridge ${path} must be one of ${values.join(', ')}`, 'MOBILE_BRIDGE_INVALID_RESPONSE')
}
